"""Initial migration

Revision ID: ab791daa28ae
Revises: 
Create Date: 2025-04-09 23:19:16.523678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab791daa28ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institutions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('institutions', 'api_request_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('institutions', 'api_request_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_institutions_id', table_name='institutions')
    op.add_column('mcq_responses', sa.Column('mcq_data', sa.Text(), nullable=False))
    op.alter_column('mcq_responses', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('mcq_responses', 'institution_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('mcq_responses', 'pdf_index_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_mcq_responses_answer_id', table_name='mcq_responses')
    op.drop_index('ix_mcq_responses_id', table_name='mcq_responses')
    op.drop_index('ix_mcq_responses_institution_id', table_name='mcq_responses')
    op.drop_index('ix_mcq_responses_pdf_index_id', table_name='mcq_responses')
    op.drop_index('ix_mcq_responses_question_id', table_name='mcq_responses')
    op.create_foreign_key(None, 'mcq_responses', 'institutions', ['institution_id'], ['id'])
    op.create_foreign_key(None, 'mcq_responses', 'pdf_indices', ['pdf_index_id'], ['id'])
    op.drop_column('mcq_responses', 'question_id')
    op.drop_column('mcq_responses', 'answer_id')
    op.add_column('pdf_indices', sa.Column('institution_id', sa.UUID(), nullable=False))
    op.alter_column('pdf_indices', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pdf_indices', 'index_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pdf_indices', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_pdf_indices_id', table_name='pdf_indices')
    op.create_foreign_key(None, 'pdf_indices', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pdf_indices', type_='foreignkey')
    op.create_index('ix_pdf_indices_id', 'pdf_indices', ['id'], unique=False)
    op.alter_column('pdf_indices', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pdf_indices', 'index_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pdf_indices', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('pdf_indices', 'institution_id')
    op.add_column('mcq_responses', sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mcq_responses', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mcq_responses', type_='foreignkey')
    op.drop_constraint(None, 'mcq_responses', type_='foreignkey')
    op.create_index('ix_mcq_responses_question_id', 'mcq_responses', ['question_id'], unique=False)
    op.create_index('ix_mcq_responses_pdf_index_id', 'mcq_responses', ['pdf_index_id'], unique=False)
    op.create_index('ix_mcq_responses_institution_id', 'mcq_responses', ['institution_id'], unique=False)
    op.create_index('ix_mcq_responses_id', 'mcq_responses', ['id'], unique=False)
    op.create_index('ix_mcq_responses_answer_id', 'mcq_responses', ['answer_id'], unique=False)
    op.alter_column('mcq_responses', 'pdf_index_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('mcq_responses', 'institution_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('mcq_responses', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('mcq_responses', 'mcq_data')
    op.create_index('ix_institutions_id', 'institutions', ['id'], unique=False)
    op.alter_column('institutions', 'api_request_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('institutions', 'api_request_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('institutions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
